import { CONFIG as _0x343930 } from "./config.js";
import { resolveStartDirection as _0xf0ad28 } from "./pure/shell.js";
import { TRAVERSAL_FIXTURE as _0x560465, houndTrialStage as _0x34fcd8, polypTrialStage as _0x580426, resolveTraversalPace as _0x4f8b6a, traversalEnemyPlan as _0x510ad6 } from "./pure/traversal.js";
import { mortarComposePlan as _0x3d11f1, mortarTrialStage as _0x51b289 } from "./pure/mortar.js";
import { ribrunFixture as _0x2203bf } from "./pure/ribrun.js";
import { TRANSFORM_FIXTURE as _0xd27c69, selectTransformFixture as _0x174853 } from "./pure/transform.js";
const I = typeof globalThis.__HB_QUERY__ == "string" ? globalThis.__HB_QUERY__ : globalThis.location !== undefined ? globalThis.location.search : "";
export const QUERY = new URLSearchParams(I);
export const IS_TRAVERSAL_SLICE = QUERY.get("slice") === "traversal";
export const IS_G2 = QUERY.get("g2") === "1";
export const IS_TRANSFORM_SLICE = QUERY.get("slice") === "transform" || IS_G2;
_0x174853(IS_G2 ? "monster-g2-neck-flip" : "transform-v1");
export const SLICE_ENEMIES_ENABLED = QUERY.get("enemies") !== "0";
export const SLICE_PACE = QUERY.get("pace") || "base";
export const HOOK_ENABLED = IS_TRAVERSAL_SLICE && QUERY.get("hook") === "1";
export const HOOK_INPUT = QUERY.get("hookinput") === "auto" ? "auto" : "key";
export const FLOW_ENABLED = IS_TRAVERSAL_SLICE && QUERY.get("flow") === "1";
export const AUTOBOUNCE_ENABLED = IS_TRAVERSAL_SLICE && QUERY.get("autobounce") === "1";
export const RIBRUN_ENABLED = IS_TRAVERSAL_SLICE && QUERY.get("ribrun") === "1";
export const ACTIVE_SLICE = IS_TRAVERSAL_SLICE ? _0x4f8b6a(SLICE_PACE, RIBRUN_ENABLED ? _0x2203bf(_0x560465) : _0x560465, {
  hook: HOOK_ENABLED,
  flow: FLOW_ENABLED
}) : null;
export const ACTIVE_FIXTURE = IS_TRANSFORM_SLICE ? _0xd27c69 : ACTIVE_SLICE;
export const ZIPPER_REVEAL = QUERY.get("zip") === "1" || QUERY.get("g1") === "0";
export const IS_G1 = ACTIVE_FIXTURE === null && !ZIPPER_REVEAL;
const c = QUERY.get("momentum");
export const MOMENTUM_ENABLED = ACTIVE_FIXTURE === null && c !== "0" && c !== "off";
const l = QUERY.get("score");
export const SCORE_ENABLED = ACTIVE_FIXTURE === null ? l !== "0" && l !== "off" : l === "1";
export const SLICE_FALLBACK_ENABLED = IS_TRAVERSAL_SLICE && QUERY.get("fallback") !== "0";
export const RUN_FALLBACK_ENABLED = ACTIVE_FIXTURE === null && QUERY.get("fallback") !== "0";
const T = QUERY.get("view");
export const VIEW_ID = _0x343930.viewScales[T] ? T : "far";
const p = IS_TRAVERSAL_SLICE ? QUERY.get("hound") : null;
export const HOUND_STAGE = p === null || p === "0" || p === "off" ? null : p === "aim" ? "aim" : p === "3" || p === "mix" ? "mix" : p === "2.5" || p === "squeeze+" ? "squeezePlus" : p === "2" || p === "combo" ? "combo" : "solo";
export const HOUND_TRIAL_STAGE = _0x34fcd8(HOUND_STAGE);
const U = IS_TRAVERSAL_SLICE ? QUERY.get("polyp") : null;
export const POLYP_STAGE = U === null || U === "0" || U === "off" ? null : U === "2" || U === "combo" ? "combo" : "solo";
export const POLYP_TRIAL_STAGE = _0x580426(POLYP_STAGE);
const C = IS_TRAVERSAL_SLICE ? QUERY.get("mortar") : null;
export const MORTAR_STAGE = C === null || C === "0" || C === "off" ? null : C === "2" || C === "combo" ? "combo" : "solo";
export const MORTAR_TRIAL_STAGE = _0x51b289(MORTAR_STAGE);
export const SLICE_ENEMY_PLAN = _0x3d11f1(_0x510ad6(ACTIVE_SLICE, HOUND_STAGE, POLYP_STAGE), MORTAR_STAGE);
export const JUICE_ENABLED = QUERY.get("juice") !== "0";
const a = QUERY.get("shell");
export const SHELL_ENABLED = a !== "0";
export const SHELL_AUTOSTART = SHELL_ENABLED && a !== "title" && (QUERY.has("testapi") || QUERY.has("selftest"));
export const START_DIRECTION_ID = _0xf0ad28(QUERY.get("title"));
export const CROUCH_ENABLED = QUERY.get("crouch") === "1";
const i = QUERY.get("aim");
export const AIM_ASSIST_ENABLED = ACTIVE_FIXTURE === null ? i !== "raw" && i !== "0" && i !== "off" : i === "assist";